Update npm-publish.yml

diff --git a/.github/workflows/npm-publish.yml b/.github/workflows/npm-publish.yml
--- a/.github/workflows/npm-publish.yml
+++ b/.github/workflows/npm-publish.yml
@@ -1,6 +1,3 @@
-# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
-# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
-
 name: Node.js Package
 
 on:
@@ -41,8 +38,19 @@ jobs:
       - name: Install Dependencies
         run: npm ci
 
-      - name: Publish to npm
+      - name: Check NPM Token Secret
+        id: check_secret
         run: |
+          if [ -z "${{ secrets.npm_token }}" ]; then
+            echo "Error: NPM Token secret is not set."
+            exit 1
+          fi
+          echo "NPM Token secret is set."
+
+      - name: Publish to npm
+        if: steps.check_secret.outcome == 'success'
+        run: |
+          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
           npm publish || exit 1
         env:
           NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
